---
title: "Análise da base RAIS"
description: |
  Esta análise tem o objetivo de analisa os salários da base RAIS.
  A análise foi desenvolvida na Semana de Data Science na Prática da Curso-r
author:
  - name: Luisa Raniro
    url: https://github.io/portfolioLuisa
date: 2021-12-07
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Esse é meu **primeiro projeto** no [*portfólio*]{.ul}.

~~Riscar um texto~~

## Lista numerada

1.  Luisa
2.  Murilo

## Imagens

!\[\](<https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pactoconsultoriajr.com%2Fanalytics-analise-de-dados-e-sua-importancia%2F&psig=AOvVaw0OWL7_TpD9X-R9Pp6HoGxz&ust=1639047915948000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJCDhL2H1PQCFQAAAAAdAAAAABAD>)

## Código em R

```{undefined echo=TRUE}
# aqui vamos colocar o código em R

1+1

```

Criamos um campo de código!

Tabela:

```{r}

knitr::kable(mtcars)

```

Imagem/grafico:

```{r, out.width="90%", fig.align='center', dpi = 300, fig.cap="Gráfico da base mtcars"}

plot(mtcars$mpg, mtcars$hp)

```

## Código em linha

Hoje é o dia `r Sys.Date()`.
